CALC5Server.c File Reference
#include `MATHCNST.H`
#include `STDDEFS.H`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include <unistd.h>
#include `CALCServer.h`
#include `ocean.h`
Classes
struct JPL_Horizons_Tbl
Macros
#define INCocean
#define VERBOSE_DEBUG
Functions
int calcinit_ (int *jobn, int *mjd, short int kflags[64], int *iret)
void calcmodl2_ (int *mjd, double *time, int *srcid, int *stnaid, int *stnbid, double *delay, double *rate, double *u, double *v, double *w, double atmos[4], double datmos[4], double *accel, double *risetime, double *settime, double xelev[2], double relev[2], double xaz[2], double raz[2], double partials[28], int *iret)
char * rad2str (double angle, char *pFormat, char *pOutStr)
char * mjd2str (long mjd, char *pstring)
char * cvrtuc (char *s)
char * cvrtlc (char *s)
int ingra (double radeg, char *rastr)
int ingdec (double decdeg, char *decstr)
int iword (char *instr, char *delim, int nword, char *outstr)
void date2str (double date, char *str)
STATUS loadOcean (char *p_stn_name, int jrow)
double ast_dopplr (double mjdtime, double u, double v, double w)
void call_calc_by_struct (PythonIn *in, PythonOut *out)
void call_calc (int date, double time, double ra, double dec, double x, double y, double z, double axis_off, int neop, double *EOP_time, double *tai_utc, double *ut1_utc, double *xpole, double *ypole, char *stnname, char *srcname)
int init_ast_dopplr (int argc, char *argv[])
double d_mathcnst_ (char *chr1_ptr, int chr1_len)
double d_ftoc_ (int *int1_ptr, char *chr1_ptr, int *int2_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
double mjd_ftoc_ (int *int1_ptr, char *chr1_ptr, int *int2_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
double f_ftoc_ (int *int1_ptr, char *chr1_ptr, int *int2_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
int i_ftoc_ (int *int1_ptr, char *chr1_ptr, int *int2_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
void c_ftoc_ (char *ret_ptr, int ret_len, int *int1_ptr, char *chr1_ptr, int *int2_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
int n_rows_ (int *int1_ptr, char *chr1_ptr, int chr1_len)
double d_fetch (int job_num, char *tbl_name, int row_num, char *keyname, char *err)
float f_fetch (int job_num, char *tbl_name, int row_num, char *keyname, char *err)
int i_fetch (int job_num, char *p_tbl_name, int row_num, char *p_keyname, char *p_err)
char * c_fetch (int job_num, char *p_tbl_name, int row_num, char *p_keyname, char *p_err)
double mjd_fetch (int job_num, char *tbl_name, int row_num, char *keyname, char *err)
int oce_fetch_ (int *istation, int *itype, double *coeffs)
void c1write_ (char *chr1_ptr, int chr1_len)
void c1log_ (char *chr1_ptr, int chr1_len)
void c2write_ (char *chr1_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
void cnwrite_ (char *chr1_ptr, char *chr2_ptr, short *p_i2char, int chr1_len, int chr2_len)
void cfwrite_ (char *chr1_ptr, char *chr2_ptr, short *p_i2char, int chr1_len, int chr2_len)
void c2logerror_ (char *chr1_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
void d1write_ (char *chr1_ptr, double *float1_ptr, int chr1_len)
void d2write_ (char *chr1_ptr, double *float1_ptr, double *float2_ptr, int chr1_len)
void c2i2writ_ (char *chr1_ptr, char *chr2_ptr, int *int1_ptr, int *int2_ptr, int chr1_len, int chr2_len)
void d10write_ (char *chr1_ptr, double *float1_ptr, double *float2_ptr, double *float3_ptr, double *float4_ptr, double *float5_ptr, double *float6_ptr, double *float7_ptr, double *float8_ptr, double *float9_ptr, double *float10_ptr, int chr1_len)
void r1write_ (char *chr1_ptr, float *float1_ptr, int chr1_len)
void i1write_ (char *chr1_ptr, int *int1_ptr, int chr1_len)
void i2write_ (char *chr1_ptr, int *int1_ptr, int *int2_ptr, int chr1_len)
int fstr2cpy_ (char *chr1_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
int fstrcmp_ (char *chr1_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
int fstrcpy_ (char *chr1_ptr, char *chr2_ptr, int chr1_len, int chr2_len)
double asteroid (double mjdtime, int icolumn)
Variables
struct JPL_Horizons_Tbl solar_target [5000]
struct JPL_Horizons_Tbl * p_ss_targ [5000]
int n_Horizons_rows
int ilog_Horizons = 1
int iparallax = 1
char Horizons_srcname [24]
char Horizons_filename [256]
int ifirst
int ilogdate = 1
char Version [48]
getCALC_arg * p_request
getCALC_res * p_result
getCALC_arg argument
getCALC_res result
struct ocean_coeffs * p_ocean_row [1000]
Macro Definition Documentation
INCocean
#define INCocean
Definition at line 10 of file CALC5Server.c.
VERBOSE_DEBUG
#define VERBOSE_DEBUG
Definition at line 13 of file CALC5Server.c.
Function Documentation
ast_dopplr()
double ast_dopplr (double mjdtime, double u, double v, double w)
Definition at line 137 of file CALC5Server.c.
References JPL_Horizons_Tbl::dec, JPL_Horizons_Tbl::deldot, JPL_Horizons_Tbl::delta, n_Horizons_rows, JPL_Horizons_Tbl::ra, JPL_Horizons_Tbl::ref_time, and solar_target.
asteroid()
double asteroid (double mjdtime, int icolumn)
Definition at line 1979 of file CALC5Server.c.
References JPL_Horizons_Tbl::dec, JPL_Horizons_Tbl::deldot, JPL_Horizons_Tbl::delta, n_Horizons_rows, JPL_Horizons_Tbl::ra, JPL_Horizons_Tbl::ref_time, and solar_target.
Referenced by d_fetch().
c1log_()
void c1log_ (char * chr1_ptr, int chr1_len)
Definition at line 1454 of file CALC5Server.c.
c1write_()
void c1write_ (char * chr1_ptr, int chr1_len)
Definition at line 1431 of file CALC5Server.c.
c2i2writ_()
void c2i2writ_ (char * chr1_ptr, char * chr2_ptr, int * int1_ptr, int * int2_ptr, int chr1_len, int chr2_len)
Definition at line 1696 of file CALC5Server.c.
c2logerror_()
void c2logerror_ (char * chr1_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 1592 of file CALC5Server.c.
c2write_()
void c2write_ (char * chr1_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 1479 of file CALC5Server.c.
c_fetch()
char* c_fetch (int job_num, char * p_tbl_name, int row_num, char * p_keyname, char * p_err)
Definition at line 1275 of file CALC5Server.c.
References getCALC_arg::axis_type_a, getCALC_arg::axis_type_b, cvrtuc(), NULL, getCALC_arg::source, and getCALC_arg::station_b.
Referenced by c_ftoc_().
c_ftoc_()
void c_ftoc_ (char * ret_ptr, int ret_len, int * int1_ptr, char * chr1_ptr, int * int2_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 931 of file CALC5Server.c.
References c_fetch().
calcinit_()
int calcinit_ (int * jobn, int * mjd, short int kflags[64], int * iret)
calcmodl2_()
void calcmodl2_ (int * mjd, double * time, int * srcid, int * stnaid, int * stnbid, double * delay, double * rate, double * u, double * v, double * w, double atmos[4], double datmos[4], double * accel, double * risetime, double * settime, double xelev[2], double relev[2], double xaz[2], double raz[2], double partials[28], int * iret)
call_calc()
void call_calc (int date, double time, double ra, double dec, double x, double y, double z, double axis_off, int neop, double * EOP_time, double * tai_utc, double * ut1_utc, double * xpole, double * ypole, char * stnname, char * srcname)
Definition at line 482 of file CALC5Server.c.
References getCALC_arg::a_x, getCALC_arg::a_y, getCALC_arg::a_z, getCALC_arg::axis_off_a, getCALC_arg::axis_off_b, getCALC_arg::axis_type_a, getCALC_arg::axis_type_b, getCALC_arg::b_x, getCALC_arg::b_y, getCALC_arg::b_z, getCALC_arg::date, getCALC_arg::ddec, JPL_Horizons_Tbl::dec, getCALC_arg::dec, getCALC_arg::depoch, getCALC_arg::dra, getCALC_arg::EOP_time, getCALC_arg::kflags, getCALC_arg::parallax, getCALC_arg::pressure_a, getCALC_arg::pressure_b, JPL_Horizons_Tbl::ra, getCALC_arg::ra, getCALC_arg::ref_frame, getCALC_arg::request_id, getCALC_arg::source, getCALC_arg::station_a, getCALC_arg::station_b, getCALC_arg::tai_utc, getCALC_arg::time, getCALC_arg::ut1_utc, getCALC_arg::xpole, and getCALC_arg::ypole.
call_calc_by_struct()
void call_calc_by_struct (PythonIn * in, PythonOut * out)
Definition at line 403 of file CALC5Server.c.
References getCALC_arg::a_x, getCALC_arg::a_y, getCALC_arg::a_z, argument, PythonIn::axis_off, getCALC_arg::axis_off_a, getCALC_arg::axis_off_b, getCALC_arg::axis_type_a, getCALC_arg::axis_type_b, getCALC_arg::b_x, getCALC_arg::b_y, getCALC_arg::b_z, getCALC_arg::date, PythonIn::date, getCALC_arg::ddec, getCALC_arg::dec, PythonIn::dec, getCALC_arg::depoch, getCALC_arg::dra, getCALC_arg::EOP_time, PythonIn::EOP_time, getCALC_arg::kflags, PythonIn::neop, getCALC_arg::parallax, getCALC_arg::pressure_a, getCALC_arg::pressure_b, getCALC_arg::ra, PythonIn::ra, getCALC_arg::ref_frame, getCALC_arg::request_id, result, getCALC_arg::source, PythonIn::srcname, getCALC_arg::station_a, getCALC_arg::station_b, PythonIn::stnname, getCALC_arg::tai_utc, PythonIn::tai_utc, getCALC_arg::time, PythonIn::time, getCALC_arg::ut1_utc, PythonIn::ut1_utc, PythonIn::x, getCALC_arg::xpole, PythonIn::xpole, PythonIn::y, getCALC_arg::ypole, PythonIn::ypole, and PythonIn::z.
cfwrite_()
void cfwrite_ (char * chr1_ptr, char * chr2_ptr, short * p_i2char, int chr1_len, int chr2_len)
Definition at line 1552 of file CALC5Server.c.
cnwrite_()
void cnwrite_ (char * chr1_ptr, char * chr2_ptr, short * p_i2char, int chr1_len, int chr2_len)
Definition at line 1514 of file CALC5Server.c.
cvrtlc()
char* cvrtlc (char * s)
Definition at line 37 of file cvrtuc.c.
Referenced by cvrtuc().
cvrtuc()
char* cvrtuc (char * s)
Definition at line 12 of file cvrtuc.c.
References cvrtlc().
Referenced by c_fetch(), d_fetch(), f_fetch(), i_fetch(), mjd_fetch(), and n_rows_().
d10write_()
void d10write_ (char * chr1_ptr, double * float1_ptr, double* float2_ptr, double* float3_ptr, double* float4_ptr, double * float5_ptr, double* float6_ptr, double* float7_ptr, double* float8_ptr, double * float9_ptr, double* float10_ptr, int chr1_len)
Definition at line 1733 of file CALC5Server.c.
d1write_()
void d1write_ (char * chr1_ptr, double * float1_ptr, int chr1_len)
Definition at line 1631 of file CALC5Server.c.
d2write_()
void d2write_ (char * chr1_ptr, double * float1_ptr, double * float2_ptr, int chr1_len)
Definition at line 1662 of file CALC5Server.c.
d_fetch()
double d_fetch (int job_num, char * tbl_name, int row_num, char * keyname, char * err)
Definition at line 1038 of file CALC5Server.c.
References getCALC_arg::a_x, getCALC_arg::a_y, getCALC_arg::a_z, asteroid(), getCALC_arg::b_x, getCALC_arg::b_y, getCALC_arg::b_z, cvrtuc(), getCALC_arg::date, date2str(), getCALC_arg::dec, Horizons_srcname, ilog_Horizons, ingdec(), ingra(), iparallax, n_Horizons_rows, getCALC_arg::parallax, getCALC_arg::ra, getCALC_arg::source, getCALC_arg::tai_utc, getCALC_arg::time, getCALC_arg::ut1_utc, getCALC_arg::xpole, and getCALC_arg::ypole.
Referenced by d_ftoc_().
d_ftoc_()
double d_ftoc_ (int * int1_ptr, char * chr1_ptr, int * int2_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 760 of file CALC5Server.c.
References d_fetch().
d_mathcnst_()
double d_mathcnst_ (char * chr1_ptr, int chr1_len)
Definition at line 699 of file CALC5Server.c.
date2str()
void date2str (double date, char * str)
Definition at line 67 of file CALC5Server.c.
References mjd2str(), and rad2str().
Referenced by d_fetch().
f_fetch()
float f_fetch (int job_num, char * tbl_name, int row_num, char * keyname, char * err)
Definition at line 1171 of file CALC5Server.c.
References getCALC_arg::axis_off_a, getCALC_arg::axis_off_b, cvrtuc(), and getCALC_arg::pressure_b.
Referenced by f_ftoc_().
f_ftoc_()
double f_ftoc_ (int * int1_ptr, char * chr1_ptr, int * int2_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 841 of file CALC5Server.c.
References f_fetch().
fstr2cpy_()
int fstr2cpy_ (char * chr1_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 1874 of file CALC5Server.c.
fstrcmp_()
int fstrcmp_ (char * chr1_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 1908 of file CALC5Server.c.
fstrcpy_()
int fstrcpy_ (char * chr1_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 1941 of file CALC5Server.c.
i1write_()
void i1write_ (char * chr1_ptr, int * int1_ptr, int chr1_len)
Definition at line 1808 of file CALC5Server.c.
i2write_()
void i2write_ (char * chr1_ptr, int * int1_ptr, int * int2_ptr, int chr1_len)
Definition at line 1839 of file CALC5Server.c.
i_fetch()
int i_fetch (int job_num, char * p_tbl_name, int row_num, char * p_keyname, char * p_err)
Definition at line 1230 of file CALC5Server.c.
References getCALC_arg::axis_off_b, and cvrtuc().
Referenced by i_ftoc_().
i_ftoc_()
int i_ftoc_ (int * int1_ptr, char * chr1_ptr, int * int2_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 889 of file CALC5Server.c.
References i_fetch().
ingdec()
int ingdec (double decdeg, char * decstr)
Definition at line 5 of file ingdec.c.
Referenced by d_fetch().
ingra()
int ingra (double radeg, char * rastr)
Definition at line 6 of file ingra.c.
Referenced by d_fetch().
init_ast_dopplr()
int init_ast_dopplr (int argc, char * argv[])
Definition at line 611 of file CALC5Server.c.
References JPL_Horizons_Tbl::dec, JPL_Horizons_Tbl::deldot, JPL_Horizons_Tbl::delta, Horizons_filename, Horizons_srcname, ifirst, iword(), n_Horizons_rows, NULL, p_ss_targ, JPL_Horizons_Tbl::ra, JPL_Horizons_Tbl::ref_time, and solar_target.
iword()
int iword (char * instr, char * delim, int nword, char * outstr)
Definition at line 7 of file iword.c.
References sindex().
Referenced by init_ast_dopplr().
loadOcean()
STATUS loadOcean (char * p_stn_name, int jrow)
Definition at line 85 of file CALC5Server.c.
References ERROR, oc_coeffs, OK, and ocean_coeffs::stn_id.
mjd2str()
char* mjd2str (long mjd, char * pstring)
Definition at line 85 of file mjd2str.c.
Referenced by date2str().
mjd_fetch()
double mjd_fetch (int job_num, char * tbl_name, int row_num, char * keyname, char * err)
Definition at line 1336 of file CALC5Server.c.
References cvrtuc(), getCALC_arg::date, getCALC_arg::EOP_time, and getCALC_arg::time.
Referenced by mjd_ftoc_().
mjd_ftoc_()
double mjd_ftoc_ (int * int1_ptr, char * chr1_ptr, int * int2_ptr, char * chr2_ptr, int chr1_len, int chr2_len)
Definition at line 800 of file CALC5Server.c.
References mjd_fetch().
n_rows_()
int n_rows_ (int * int1_ptr, char * chr1_ptr, int chr1_len)
Definition at line 980 of file CALC5Server.c.
References cvrtuc(), and getCALC_arg::pressure_b.
oce_fetch_()
int oce_fetch_ (int * istation, int * itype, double * coeffs)
Definition at line 1371 of file CALC5Server.c.
References ocean_coeffs::sithocam, ocean_coeffs::sithocph, ocean_coeffs::sitocamp, and ocean_coeffs::sitocphs.
r1write_()
void r1write_ (char * chr1_ptr, float * float1_ptr, int chr1_len)
Definition at line 1777 of file CALC5Server.c.
rad2str()
char* rad2str (double angle, char * pFormat, char * pOutStr)
Definition at line 279 of file time2str.c.
References rad2strg(), and time2str().
Referenced by date2str(), and time2str().
Variable Documentation
argument
getCALC_arg argument
Definition at line 54 of file CALC5Server.c.
Referenced by call_calc_by_struct().
Horizons_filename
char Horizons_filename[256]
Definition at line 45 of file CALC5Server.c.
Referenced by init_ast_dopplr().
Horizons_srcname
char Horizons_srcname[24]
Definition at line 44 of file CALC5Server.c.
Referenced by d_fetch(), and init_ast_dopplr().
ifirst
int ifirst
Definition at line 47 of file CALC5Server.c.
Referenced by init_ast_dopplr().
ilog_Horizons
int ilog_Horizons = 1
Definition at line 42 of file CALC5Server.c.
Referenced by d_fetch().
ilogdate
int ilogdate = 1
Definition at line 47 of file CALC5Server.c.
iparallax
int iparallax = 1
Definition at line 43 of file CALC5Server.c.
Referenced by d_fetch().
n_Horizons_rows
int n_Horizons_rows
Definition at line 41 of file CALC5Server.c.
Referenced by ast_dopplr(), asteroid(), d_fetch(), and init_ast_dopplr().
p_ocean_row
struct ocean_coeffs* p_ocean_row[1000]
Definition at line 57 of file CALC5Server.c.
p_request
getCALC_arg* p_request
Definition at line 51 of file CALC5Server.c.
p_result
getCALC_res* p_result
Definition at line 52 of file CALC5Server.c.
p_ss_targ
struct JPL_Horizons_Tbl * p_ss_targ[5000]
Referenced by init_ast_dopplr().
result
getCALC_res result
Definition at line 55 of file CALC5Server.c.
Referenced by call_calc_by_struct().
solar_target
struct JPL_Horizons_Tbl solar_target[5000]
Referenced by ast_dopplr(), asteroid(), and init_ast_dopplr().
Version
char Version[48]
Definition at line 50 of file CALC5Server.c.