calcmodl2.f File Reference
Functions/Subroutines
subroutine calcmodl2 (MJD, TIME, SRCID, STNAID, STNBID, DELAY, RATE, U, V, W, ATMOS, DATMOS, ACCEL, RISETIME, SETTIME, XELEV, RELEV, XAZ, RAZ, PARTIALS, IRETURN)
subroutine jpl314 (C_TERM, TERM4, GEO_SC, R1MPT1, R2MPT1, GRAVDLY)
Function/Subroutine Documentation
calcmodl2()
subroutine calcmodl2 (integer*4 MJD, real*8 TIME, integer*4 SRCID, integer*4 STNAID, integer*4 STNBID, real*8 DELAY, real*8 RATE, real*8 U, real*8 V, real*8 W, real*8, dimension(2,2) ATMOS, real*8, dimension(2,2) DATMOS, real*8 ACCEL, real*8 RISETIME, real*8 SETTIME, real*8, dimension(2) XELEV, real*8, dimension(2) RELEV, real*8, dimension(2) XAZ, real*8, dimension(2) RAZ, real*8, dimension(28) PARTIALS, integer*4 IRETURN)
Definition at line 5 of file calcmodl2.f.
References drivr(), jpl314(), and mjd2day().
jpl314()
subroutine jpl314 (real*8 C_TERM, real*8 TERM4, real*8, dimension(3) GEO_SC, real*8, dimension(3) R1MPT1, real*8, dimension(3) R2MPT1, real*8 GRAVDLY)
Definition at line 483 of file calcmodl2.f.
Referenced by calcmodl2().