calcinit.f File Reference
Functions/Subroutines
subroutine calcinit (JOBN, MJD, KFLAGS, IRETURN)
Function/Subroutine Documentation
calcinit()
subroutine calcinit (integer*4 JOBN, integer*4 MJD, integer*2, dimension(64) KFLAGS, integer*4 IRETURN)
Definition at line 2 of file calcinit.f.
References initl(), pepa(), puta(), ut1a(), and woba().