catiu.f File Reference
Functions/Subroutines
subroutine atima
subroutine atimi
subroutine atime (UTC, XJD, AT, DUTCAT)
Function/Subroutine Documentation
atima()
subroutine atima ()
Definition at line 2 of file catiu.f.
References adda().
atime()
subroutine atime (real*8 UTC, real*8 XJD, real*8 AT, real*8 DUTCAT)
Definition at line 164 of file catiu.f.
Referenced by drivr().
atimi()
subroutine atimi ()
Definition at line 47 of file catiu.f.
References ckill(), get4(), and puta().
Referenced by initl().