catmm.f File Reference
Functions/Subroutines
subroutine atma
subroutine atmi
subroutine atmg (R2000, STAR, EARTH, TCTOCF, SITEV, AZ, ELEV, STAR_ABERRATED)
subroutine atmp (ELEV, AZ, SITLAT, SITHEIGHT, XJD, CT, dATMCdh)
subroutine atmc (ZPATH, DATMC)
subroutine nhmf2 (epoch, latitude, height, elev, hmf)
subroutine nwmf2 (latitude, elev, wmf)
subroutine sastd (P, PDOT, RLAT, SITEHT, dPdh, ZD, ZDDOT, dZDdh)
subroutine sastw (RH, TC, RHDOT, TCDOT, ZW, ZWDOT)
Function/Subroutine Documentation
atma()
subroutine atma ()
Definition at line 2 of file catmm.f.
References adda(), addr(), and delr().
atmc()
subroutine atmc (real*8, dimension(2) ZPATH, real*8, dimension(2,2) DATMC)
Definition at line 769 of file catmm.f.
References put4().
Referenced by drivr().
atmg()
subroutine atmg (real*8, dimension(3,3,3) R2000, real*8, dimension(3) STAR, real*8, dimension(3,3) EARTH, real*8, dimension(3,3,2) TCTOCF, real*8, dimension(3,2) SITEV, real*8, dimension(2,2) AZ, real*8, dimension(2,2) ELEV, real*8, dimension(3,2) STAR_ABERRATED)
Definition at line 178 of file catmm.f.
References mtran(), put4(), vecad(), vecrt(), and vunit().
Referenced by drivr().
atmi()
subroutine atmi ()
Definition at line 97 of file catmm.f.
References puta().
Referenced by initl().
atmp()
subroutine atmp (real*8, dimension(2,2) ELEV, real*8, dimension(2,2) AZ, real*8, dimension(2) SITLAT, real*8, dimension(2) SITHEIGHT, real*8 XJD, real*8 CT, real*8, dimension(2,2) dATMCdh)
Definition at line 442 of file catmm.f.
References get4(), nhmf2(), nwmf2(), put4(), sastd(), and sastw().
Referenced by drivr().
nhmf2()
subroutine nhmf2 (real*8 epoch, real*8 latitude, real*8 height, real*8 elev, real*8, dimension(2) hmf)
Definition at line 925 of file catmm.f.
Referenced by atmp().
nwmf2()
subroutine nwmf2 (real*8 latitude, real*8 elev, real*8, dimension(2) wmf)
Definition at line 1172 of file catmm.f.
Referenced by atmp().
sastd()
subroutine sastd (real*8 P, real*8 PDOT, real*8 RLAT, real*8 SITEHT, real*8 dPdh, real*8 ZD, real*8 ZDDOT, real*8 dZDdh)
Definition at line 1300 of file catmm.f.
Referenced by atmp().
sastw()
subroutine sastw (real*8 RH, real*8 TC, real*8 RHDOT, real*8 TCDOT, real*8 ZW, real*8 ZWDOT)
Definition at line 1376 of file catmm.f.
Referenced by atmp().