caxom.f File Reference
Functions/Subroutines
subroutine axoa
subroutine axoi
subroutine axog (KAXIS, R2000, SITLAT, STAR, TCTOCF, SITEV, AXOFF, EARTH, AZ, ELEV, STAR_ABERRATED, SITHEIGHT, axis2000, daxis2000)
subroutine axop (AXOFF, dATMCdh)
subroutine axoc (AXOFF, DAXOC)
double precision function sbend (El_rad, Temp_K, Humid_F, Press_Hg)
subroutine fbox (TNCP, TCAXIS, CTCSTR, AZ, DAZ, ZA, DZA, RANGL, DRANGL)
Function/Subroutine Documentation
axoa()
subroutine axoa ()
Definition at line 2 of file caxom.f.
References adda(), addr(), and delr().
axoc()
subroutine axoc (real*8, dimension(2) AXOFF, real*8, dimension(2,2) DAXOC)
Definition at line 1054 of file caxom.f.
References put4().
Referenced by drivr().
axog()
subroutine axog (integer*2, dimension(2) KAXIS, real*8, dimension(3,3,3) R2000, real*8, dimension(2) SITLAT, real*8, dimension(3) STAR, real*8, dimension(3,3,2) TCTOCF, real*8, dimension(3,2) SITEV, real*8, dimension(2) AXOFF, real*8, dimension(3,3) EARTH, real*8, dimension(2,2) AZ, real*8, dimension(2,2) ELEV, real*8, dimension(3,2) STAR_ABERRATED, real*8, dimension(2) SITHEIGHT, real*8, dimension(3,2) axis2000, real*8, dimension(3,2) daxis2000)
Definition at line 206 of file caxom.f.
References ckill(), crosp(), fbox(), get4(), mtran(), put4(), vecad(), and vecrt().
Referenced by drivr().
axoi()
subroutine axoi ()
Definition at line 108 of file caxom.f.
References puta().
Referenced by initl().
axop()
subroutine axop (real*8, dimension(2) AXOFF, real*8, dimension(2,2) dATMCdh)
Definition at line 874 of file caxom.f.
References put4().
Referenced by drivr().
fbox()
subroutine fbox (real*8, dimension(3) TNCP, real*8, dimension(3) TCAXIS, real*8, dimension(3) CTCSTR, real*8 AZ, real*8 DAZ, real*8 ZA, real*8 DZA, real*8 RANGL, real*8 DRANGL)
Definition at line 1346 of file caxom.f.
References drott(), madd2(), mmul2(), rotat(), and vecrt().
Referenced by axog().
sbend()
double precision function sbend (real*8 El_rad, real*8 Temp_K, real*8 Humid_F, real*8 Press_Hg)
Definition at line 1254 of file caxom.f.