cctiu.f File Reference
Functions/Subroutines
subroutine ctima
subroutine ctimi
subroutine ctimg (AT, CFSITE, SITLON, UTC, XJD, CT, DATDCT, DLPGR)
Function/Subroutine Documentation
ctima()
subroutine ctima ()
Definition at line 2 of file cctiu.f.
References adda(), and addr().
ctimg()
subroutine ctimg (real*8 AT, real*8, dimension(3,2) CFSITE, real*8, dimension(2) SITLON, real*8 UTC, real*8 XJD, real*8 CT, real*8 DATDCT, real*8 DLPGR)
Definition at line 194 of file cctiu.f.
References put4().
Referenced by drivr().
ctimi()
subroutine ctimi ()
Definition at line 56 of file cctiu.f.
References ckill(), get4(), and puta().
Referenced by initl().