cdiuu.f File Reference
Functions/Subroutines
subroutine dirna
subroutine dirnl (DATDCT, DPSI, DUT1AT, EPS, DEPS, FA, UT1, XJD, DIURNV, GAST, GMST, GASTD, RS)
subroutine eqeg (gmst, dpsi, eps, epsmd, omega, gast, gastd)
subroutine dirnc (gastd, dut1p)
Function/Subroutine Documentation
dirna()
subroutine dirna ()
Definition at line 2 of file cdiuu.f.
References addr(), and delr().
dirnc()
subroutine dirnc (real*8 gastd, real*8, dimension(2,2) dut1p)
Definition at line 385 of file cdiuu.f.
References put4().
Referenced by drivr().
dirnl()
subroutine dirnl (real*8 DATDCT, real*8, dimension(2) DPSI, real*8 DUT1AT, real*8, dimension(2) EPS, real*8, dimension(2) DEPS, real*8, dimension(5) FA, real*8 UT1, real*8 XJD, real*8 DIURNV, real*8, dimension(2) GAST, real*8 GMST, real*8 GASTD, real*8, dimension(3,3,3) RS)
Definition at line 53 of file cdiuu.f.
References ddrot(), drott(), eqeg(), and rotat().
Referenced by drivr().
eqeg()
subroutine eqeg (real*8 gmst, real*8 dpsi, real*8 eps, real*8 epsmd, real*8 omega, real*8, dimension(2) gast, real*8 gastd)
Definition at line 283 of file cdiuu.f.
Referenced by dirnl().