cetdm.f File Reference
Functions/Subroutines
subroutine etda
subroutine etdi
subroutine etdg (R2000, SITLAT, SITLON, SUN, TCTOCF, RTTOCF, USITEP, USITEV, XMOON, EARTH, GAST, STAR, fa, fad, cent, GEOLAT, TIDEP, TIDEV)
subroutine etdp (R2000, SITLAT, STAR, TCTOCF)
subroutine etdc (TIDEP, TIDEV, STAR)
subroutine etdc8 (R2000, SITLAT, SITLON, SUN, TCTOCF, USITEP, USITEV, XMOON, EARTH, GAST, STAR, fa, fad, cent, TD82P, TD82V)
Function/Subroutine Documentation
etda()
subroutine etda ()
Definition at line 2 of file cetdm.f.
References adda(), addr(), and delr().
etdc()
subroutine etdc (real*8, dimension(3,2) TIDEP, real*8, dimension(3,2) TIDEV, real*8, dimension(3) STAR)
Definition at line 2010 of file cetdm.f.
References put4(), and vecsb().
Referenced by drivr().
etdc8()
subroutine etdc8 (real*8, dimension(3,3,3) R2000, real*8, dimension(2) SITLAT, real*8, dimension(2) SITLON, real*8, dimension(3,2) SUN, real*8, dimension(3,3,2) TCTOCF, real*8, dimension(3,2) USITEP, real*8, dimension(3,2) USITEV, real*8, dimension(3,2) XMOON, real*8, dimension(3,3) EARTH, real*8, dimension(2) GAST, real*8, dimension(3) STAR, real*8, dimension(5) fa, real*8, dimension(5) fad, real*8 cent, real*8, dimension(3,2) TD82P, real*8, dimension(3,2) TD82V)
Definition at line 2168 of file cetdm.f.
References vecad(), vecrt(), and vunit().
Referenced by etdg().
etdg()
subroutine etdg (real*8, dimension(3,3,3) R2000, real*8, dimension(2) SITLAT, real*8, dimension(2) SITLON, real*8, dimension(3,2) SUN, real*8, dimension(3,3,2) TCTOCF, real*8, dimension(3,3,2) RTTOCF, real*8, dimension(3,2) USITEP, real*8, dimension(3,2) USITEV, real*8, dimension(3,2) XMOON, real*8, dimension(3,3) EARTH, real*8, dimension(2) GAST, real*8, dimension(3) STAR, real*8, dimension(5) fa, real*8, dimension(5) fad, real*8 cent, real*8, dimension(2) GEOLAT, real*8, dimension(3,2) TIDEP, real*8, dimension(3,2) TIDEV)
Definition at line 221 of file cetdm.f.
References etdc8(), mtran(), vecad(), vecrt(), and vunit().
Referenced by drivr().
etdi()
subroutine etdi ()
Definition at line 101 of file cetdm.f.
References puta().
Referenced by initl().
etdp()
subroutine etdp (real*8, dimension(3,3,3) R2000, real*8, dimension(2) SITLAT, real*8, dimension(3) STAR, real*8, dimension(3,3,2) TCTOCF)
Definition at line 1882 of file cetdm.f.
References put4().
Referenced by drivr().