cinit.f File Reference
Functions/Subroutines
subroutine initl (KOUNT)
Function/Subroutine Documentation
initl()
subroutine initl (integer*4 KOUNT)
Definition at line 2 of file cinit.f.
References atimi(), atmi(), axoi(), ckill(), ctimi(), etdi(), get4(), mvrec(), nuti(), ocei(), pepi(), plxi(), prei(), ptdi(), siti(), stai(), stri(), theri(), ut1i(), wobi(), and wridr().
Referenced by calcinit().