ckill.f File Reference
Functions/Subroutines
subroutine ckill (LNAME, I1, I2)
Function/Subroutine Documentation
ckill()
subroutine ckill (integer*2, dimension(3) LNAME, integer*2 I1, integer*2 I2)
Definition at line 2 of file ckill.f.
References finis(), and quit_calc().
Referenced by atimi(), axog(), ctimi(), initl(), obsnt(), ocei(), ocnin(), prei(), ptdi(), sitblk(), sitg(), siti(), strg(), stri(), strin(), ut1i(), ut1mu(), utctm(), uvg(), wobi(), and wobmu().