cm20u.f File Reference
Functions/Subroutines
subroutine m2000a
subroutine m2000 (RDNP, RN, RP, RS, RW, TSKIP, R2000)
Function/Subroutine Documentation
m2000()
subroutine m2000 (real*8, dimension(3,3) RDNP, real*8, dimension(3,3,2) RN, real*8, dimension(3,3,2) RP, real*8, dimension(3,3,3) RS, real*8, dimension(3,3,2) RW, integer*4 TSKIP, real*8, dimension(3,3,3) R2000)
Definition at line 50 of file cm20u.f.
References madd3(), madd4(), madd5(), mmul5(), and put4().
Referenced by drivr().
m2000a()
subroutine m2000a ()
Definition at line 2 of file cm20u.f.
References addr().