cmatu.f File Reference
Functions/Subroutines
subroutine rotat (THETA, I, R)
subroutine drott (THETA, DTHETA, I, DR)
subroutine ddrot (THETA, DDTHTA, I, DDR)
subroutine d3rot (THETA, D3THET, I, D3R)
subroutine mmul2 (A, B, C)
subroutine mmul3 (A, B, C, D)
subroutine mmul5 (A, B, C, D, E, F)
subroutine madd2 (A, B, C)
subroutine madd3 (A, B, C, D)
subroutine madd4 (A, B, C, D, E)
subroutine madd5 (A, B, C, D, E, F)
subroutine mtran (A, B)
subroutine vecrt (A, V, RV)
Function/Subroutine Documentation
d3rot()
subroutine d3rot (real*8 THETA, real*8 D3THET, integer*2 I, real*8, dimension(3,3) D3R)
Definition at line 455 of file cmatu.f.
Referenced by ut1p().
ddrot()
subroutine ddrot (real*8 THETA, real*8 DDTHTA, integer*2 I, real*8, dimension(3,3) DDR)
Definition at line 302 of file cmatu.f.
Referenced by dirnl(), ut1p(), and wobp().
drott()
subroutine drott (real*8 THETA, real*8 DTHETA, integer*2 I, real*8, dimension(3,3) DR)
Definition at line 150 of file cmatu.f.
Referenced by dirnl(), fbox(), nutg(), preg(), prep(), ut1p(), wobg(), and wobp().
madd2()
subroutine madd2 (real*8, dimension(3,3) A, real*8, dimension(3,3) B, real*8, dimension(3,3) C)
Definition at line 851 of file cmatu.f.
Referenced by fbox(), nutp(), wobg(), and wobp().
madd3()
subroutine madd3 (real*8, dimension(3,3) A, real*8, dimension(3,3) B, real*8, dimension(3,3) C, real*8, dimension(3,3) D)
Definition at line 930 of file cmatu.f.
Referenced by m2000(), nutg(), preg(), and prep().
madd4()
subroutine madd4 (real*8, dimension(3,3) A, real*8, dimension(3,3) B, real*8, dimension(3,3) C, real*8, dimension(3,3) D, real*8, dimension(3,3) E)
Definition at line 1011 of file cmatu.f.
Referenced by m2000(), and wobp().
madd5()
subroutine madd5 (real*8, dimension(3,3) A, real*8, dimension(3,3) B, real*8, dimension(3,3) C, real*8, dimension(3,3) D, real*8, dimension(3,3) E, real*8, dimension(3,3) F)
Definition at line 1090 of file cmatu.f.
Referenced by m2000().
mmul2()
subroutine mmul2 (real*8, dimension(3,3) A, real*8, dimension(3,3) B, real*8, dimension(3,3) C)
Definition at line 607 of file cmatu.f.
Referenced by fbox(), mmul3(), siti(), wobg(), and wobp().
mmul3()
subroutine mmul3 (real*8, dimension(3,3) A, real*8, dimension(3,3) B, real*8, dimension(3,3) C, real*8, dimension(3,3) D)
Definition at line 689 of file cmatu.f.
References mmul2().
Referenced by mmul5(), nutg(), preg(), and prep().
mmul5()
subroutine mmul5 (real*8, dimension(3,3) A, real*8, dimension(3,3) B, real*8, dimension(3,3) C, real*8, dimension(3,3) D, real*8, dimension(3,3) E, real*8, dimension(3,3) F)
Definition at line 767 of file cmatu.f.
References mmul3().
Referenced by m2000(), nutp(), prep(), ut1p(), and wobp().
mtran()
subroutine mtran (real*8, dimension(3,3) A, real*8, dimension(3,3) B)
Definition at line 1175 of file cmatu.f.
Referenced by atmg(), axog(), and etdg().
rotat()
subroutine rotat (real*8 THETA, integer*2 I, real*8, dimension(3,3) R)
Definition at line 2 of file cmatu.f.
Referenced by dirnl(), drivr(), fbox(), nutg(), preg(), siti(), and wobg().
vecrt()
subroutine vecrt (real*8, dimension(3,3) A, real*8, dimension(3) V, real*8, dimension(3) RV)
Definition at line 1252 of file cmatu.f.
Referenced by atmg(), axog(), etdc8(), etdg(), fbox(), nutp(), oceg(), prep(), ptdg(), rosit(), ut1p(), and wobp().