cnutm.f File Reference
Functions/Subroutines
subroutine nuta
subroutine nuti
subroutine nutg (cent, fa, fad, TSKIP, DEPS, DPSI, EPS, EPSMNR, RN, NUTDIF, FUKU)
subroutine nutp (CFBASE, DEPS, DPSI, EPS, GAST, RDNP, RN, RP, RS, RW, STAR, DNUTP)
subroutine nutc (NUTDIF, DNUTP, FUKU)
subroutine nutw (CENT, fa, fad, DPSI, DEPS)
subroutine nutfa (xjd, ct, cent, fa, fad)
subroutine ksv_1996_3 (CENT, fa, fad, dpsi_ls, deps_ls, dpsi_plan, deps_plan, dpsi_fcn, deps_fcn, dpsi_prec, deps_prec, dpsi_tot, deps_tot)
subroutine ls_nut (CENT, fa, fad, dpsi_ls, deps_ls)
subroutine ls_angles (CENT, ls_arg, ls_argdot)
subroutine eval_ls_nut (CENT, ls_arg, ls_argdot, dpsi_ls, deps_ls)
subroutine plan_nut (CENT, dpsi, deps)
subroutine eval_plan_nut (plan_arg, plan_rat, dpsi, deps)
subroutine plan_angles (CENT, plan_arg, plan_rat)
subroutine fcn_nut (CENT, dpsi_fcn, deps_fcn)
subroutine prec_nut (CENT, dpsi_prec, deps_prec)
Function/Subroutine Documentation
eval_ls_nut()
subroutine eval_ls_nut (real*8 CENT, real*8, dimension(5) ls_arg, real*8, dimension(5) ls_argdot, real*8, dimension(2) dpsi_ls, real*8, dimension(2) deps_ls)
Definition at line 1988 of file cnutm.f.
Referenced by ls_nut().
eval_plan_nut()
subroutine eval_plan_nut (real*8, dimension(10) plan_arg, real*8, dimension(10) plan_rat, real*8, dimension(2) dpsi, real*8, dimension(2) deps)
Definition at line 2530 of file cnutm.f.
Referenced by plan_nut().
fcn_nut()
subroutine fcn_nut (real*8 CENT, real*8, dimension(2) dpsi_fcn, real*8, dimension(2) deps_fcn)
Definition at line 2916 of file cnutm.f.
ksv_1996_3()
subroutine ksv_1996_3 (real*8 CENT, real*8, dimension(5) fa, real*8, dimension(5) fad, real*8, dimension(2) dpsi_ls, real*8, dimension(2) deps_ls, real*8, dimension(2) dpsi_plan, real*8, dimension(2) deps_plan, real*8, dimension(2) dpsi_fcn, real*8, dimension(2) deps_fcn, real*8, dimension(2) dpsi_prec, real*8, dimension(2) deps_prec, real*8, dimension(2) dpsi_tot, real*8, dimension(2) deps_tot)
Definition at line 1635 of file cnutm.f.
References ls_nut(), plan_nut(), and prec_nut().
Referenced by nutg().
ls_angles()
subroutine ls_angles (real*8 CENT, real*8, dimension(5) ls_arg, real*8, dimension(5) ls_argdot)
Definition at line 1850 of file cnutm.f.
ls_nut()
subroutine ls_nut (real*8 CENT, real*8, dimension(5) fa, real*8, dimension(5) fad, real*8, dimension(2) dpsi_ls, real*8, dimension(2) deps_ls)
Definition at line 1728 of file cnutm.f.
References eval_ls_nut().
Referenced by ksv_1996_3().
nuta()
subroutine nuta ()
Definition at line 2 of file cnutm.f.
References adda(), addr(), and delr().
nutc()
subroutine nutc (real*8, dimension(2,2) NUTDIF, real*8, dimension(2,2) DNUTP, real*8, dimension(2) FUKU)
Definition at line 978 of file cnutm.f.
References put4().
Referenced by drivr().
nutfa()
subroutine nutfa (real*8 xjd, real*8 ct, real*8 cent, real*8, dimension(5) fa, real*8, dimension(5) fad)
Definition at line 1479 of file cnutm.f.
Referenced by drivr(), and ut1i().
nutg()
subroutine nutg (real*8 cent, real*8, dimension(5) fa, real*8, dimension(5) fad, integer*4 TSKIP, real*8, dimension(2) DEPS, real*8, dimension(2) DPSI, real*8, dimension(2) EPS, real*8 EPSMNR, real*8, dimension(3,3,2) RN, real*8, dimension(2,2) NUTDIF, real*8, dimension(2) FUKU)
Definition at line 267 of file cnutm.f.
References drott(), ksv_1996_3(), madd3(), mmul3(), nutw(), put4(), and rotat().
Referenced by drivr().
nuti()
subroutine nuti ()
Definition at line 156 of file cnutm.f.
References puta().
Referenced by initl().
nutp()
subroutine nutp (real*8, dimension(3) CFBASE, real*8, dimension(2) DEPS, real*8, dimension(2) DPSI, real*8, dimension(2) EPS, real*8, dimension(2) GAST, real*8, dimension(3,3) RDNP, real*8, dimension(3,3,2) RN, real*8, dimension(3,3,2) RP, real*8, dimension(3,3,3) RS, real*8, dimension(3,3,2) RW, real*8, dimension(3) STAR, real*8, dimension(2,2) DNUTP)
Definition at line 681 of file cnutm.f.
References madd2(), mmul5(), put4(), and vecrt().
Referenced by drivr().
nutw()
subroutine nutw (real*8 CENT, real*8, dimension(5) fa, real*8, dimension(5) fad, real*8, dimension(2) DPSI, real*8, dimension(2) DEPS)
Definition at line 1300 of file cnutm.f.
Referenced by nutg().
plan_angles()
subroutine plan_angles (real*8 CENT, real*8, dimension(10) plan_arg, real*8, dimension(10) plan_rat)
Definition at line 2769 of file cnutm.f.
Referenced by plan_nut().
plan_nut()
subroutine plan_nut (real*8 CENT, real*8, dimension(2) dpsi, real*8, dimension(2) deps)
Definition at line 2472 of file cnutm.f.
References eval_plan_nut(), and plan_angles().
Referenced by ksv_1996_3().
prec_nut()
subroutine prec_nut (real*8 CENT, real*8, dimension(2) dpsi_prec, real*8, dimension(2) deps_prec)
Definition at line 3050 of file cnutm.f.
Referenced by ksv_1996_3().