cobse.f File Reference
Functions/Subroutines
subroutine obsnt (KOUNT, KEND)
Function/Subroutine Documentation
obsnt()
subroutine obsnt (integer*4 KOUNT, integer*4 KEND)
Definition at line 2 of file cobse.f.
References ckill(), finis(), get4(), geta(), geti(), and mvrec().