cocem.f File Reference
Functions/Subroutines
subroutine ocea
subroutine ocei
subroutine oceg (CFSITE, UT1, OCEAMP, OCEPHS, R2000, XJD, TCTOCF, TSKIP, XLOADP, XLOADV)
subroutine ocep
subroutine ocec (STAR)
subroutine ocarg (UT1, XJD, ANGLE)
Function/Subroutine Documentation
ocarg()
subroutine ocarg (real*8 UT1, real*8 XJD, real*8, dimension(11) ANGLE)
Definition at line 778 of file cocem.f.
Referenced by oceg().
ocea()
subroutine ocea ()
Definition at line 2 of file cocem.f.
References adda(), and addr().
ocec()
subroutine ocec (real*8, dimension(3) STAR)
Definition at line 621 of file cocem.f.
References dotp(), put4(), and vecsb().
Referenced by drivr().
oceg()
subroutine oceg (real*8, dimension(3,2) CFSITE, real*8 UT1, real*8, dimension(11,3,2) OCEAMP, real*8, dimension(11,3,2) OCEPHS, real*8, dimension(3,3,3) R2000, real*8 XJD, real*8, dimension(3,3,2) TCTOCF, integer*4 TSKIP, real*8, dimension(3,2) XLOADP, real*8, dimension(3,2) XLOADV)
Definition at line 188 of file cocem.f.
References ocarg(), put4(), vecad(), and vecrt().
Referenced by drivr().
ocei()
subroutine ocei ()
Definition at line 82 of file cocem.f.
References ckill(), and puta().
Referenced by initl().
ocep()
subroutine ocep ()
Definition at line 611 of file cocem.f.
Referenced by drivr().