cpepu.f File Reference
Functions/Subroutines
subroutine pepa
subroutine pepi
subroutine pep (XJD, CT, TSKIP, EARTH, SUN, XMOON)
subroutine pleph (ET, NTARG, NCENT, RRD)
subroutine interp (BUF, T, NCF, NCM, NA, IFL, PV)
subroutine split (TT, FR)
subroutine state (ET2, LIST, PV, PNUT)
Function/Subroutine Documentation
interp()
subroutine interp (real*8, dimension(ncf,ncm,*) BUF, real*8, dimension(2) T, integer*4 NCF, integer*4 NCM, integer*4 NA, integer*4 IFL, real*8, dimension(ncm,*) PV)
Definition at line 668 of file cpepu.f.
Referenced by state().
pep()
subroutine pep (real*8 XJD, real*8 CT, integer*4 TSKIP, real*8, dimension(3,3) EARTH, real*8, dimension(3,2) SUN, real*8, dimension(3,2) XMOON)
Definition at line 193 of file cpepu.f.
References pleph(), and put4().
Referenced by drivr().
pepa()
subroutine pepa ()
Definition at line 2 of file cpepu.f.
References adda(), addr(), and dela().
Referenced by calcinit().
pepi()
subroutine pepi ()
Definition at line 75 of file cpepu.f.
References puta().
Referenced by initl().
pleph()
subroutine pleph (real*8 ET, integer*4 NTARG, integer*4 NCENT, real*8, dimension(6) RRD)
Definition at line 497 of file cpepu.f.
References state().
Referenced by pep().
split()
subroutine split (real*8 TT, real*8, dimension(2) FR)
Definition at line 770 of file cpepu.f.
Referenced by state().
state()
subroutine state (real*8, dimension(2) ET2, integer*4, dimension(12) LIST, real*8, dimension(6,12) PV, real*8, dimension(4) PNUT)
Definition at line 801 of file cpepu.f.
References interp(), and split().
Referenced by pleph().