cprem.f File Reference
Functions/Subroutines
subroutine prea
subroutine prei
subroutine preg (CT, EPSMNR, XJD, RP)
subroutine prep (CFBASE, EPSMNR, RDNP, RN, RS, RW, STAR)
subroutine prec
Function/Subroutine Documentation
prea()
subroutine prea ()
Definition at line 2 of file cprem.f.
References adda(), and addr().
prec()
subroutine prec ()
Definition at line 764 of file cprem.f.
preg()
subroutine preg (real*8 CT, real*8 EPSMNR, real*8 XJD, real*8, dimension(3,3,2) RP)
Definition at line 189 of file cprem.f.
References drott(), madd3(), mmul3(), and rotat().
Referenced by drivr().
prei()
subroutine prei ()
Definition at line 72 of file cprem.f.
References ckill(), get4(), and puta().
Referenced by initl().
prep()
subroutine prep (real*8, dimension(3) CFBASE, real*8 EPSMNR, real*8, dimension(3,3) RDNP, real*8, dimension(3,3,2) RN, real*8, dimension(3,3,3) RS, real*8, dimension(3,3,2) RW, real*8, dimension(3) STAR)
Definition at line 502 of file cprem.f.
References drott(), madd3(), mmul3(), mmul5(), put4(), and vecrt().
Referenced by drivr().