cptdm.f File Reference
Functions/Subroutines
subroutine ptda
subroutine ptdi
subroutine ptdg (SITLAT, SITLON, SITRAD, WOBXR, WOBYR, DIURNV, TCTOCF, R2000, CENT, POLTDP, POLTDV)
subroutine ptdp (STAR)
subroutine ptdc (STAR)
Function/Subroutine Documentation
ptda()
subroutine ptda ()
Definition at line 2 of file cptdm.f.
References adda(), and addr().
ptdc()
subroutine ptdc (real*8, dimension(3) STAR)
Definition at line 633 of file cptdm.f.
References put4(), and vecsb().
Referenced by drivr().
ptdg()
subroutine ptdg (real*8, dimension(2) SITLAT, real*8, dimension(2) SITLON, real*8, dimension(2) SITRAD, real*8 WOBXR, real*8 WOBYR, real*8 DIURNV, real*8, dimension(3,3,2) TCTOCF, real*8, dimension(3,3,3) R2000, real*8 CENT, real*8, dimension(3,2) POLTDP, real*8, dimension(3,2) POLTDV)
Definition at line 161 of file cptdm.f.
References vecrt().
Referenced by drivr().
ptdi()
subroutine ptdi ()
Definition at line 72 of file cptdm.f.
References ckill(), and puta().
Referenced by initl().
ptdp()
subroutine ptdp (real*8, dimension(3) STAR)
Definition at line 512 of file cptdm.f.
References put4(), and vecsb().
Referenced by drivr().