csitu.f File Reference
Functions/Subroutines
subroutine sitcr (TIDEP, TIDEV, USITEP, USITEV, XLOADP, XLOADV, EPBASE, SITEP, SITEV, POLTDP, POLTDV)
Function/Subroutine Documentation
sitcr()
subroutine sitcr (real*8, dimension(3,2) TIDEP, real*8, dimension(3,2) TIDEV, real*8, dimension(3,2) USITEP, real*8, dimension(3,2) USITEV, real*8, dimension(3,2) XLOADP, real*8, dimension(3,2) XLOADV, real*8, dimension(3,2) EPBASE, real*8, dimension(3,2) SITEP, real*8, dimension(3,2) SITEV, real*8, dimension(3,2) POLTDP, real*8, dimension(3,2) POLTDV)
Definition at line 3 of file csitu.f.
References vecad(), and vecsb().
Referenced by drivr().