csitm.f File Reference
Functions/Subroutines
subroutine sita
subroutine siti
subroutine sitg (AXOFF, CFBASE, CFLAT, CFLON, CFSITE, CFSITN, KAXIS, OCEAMP, OCEPHS, SITLAT, SITLON, SITRAD, TCTOCF, RTTOCF, ZPATH, SITHEIGHT, GEOLAT)
subroutine sitp (R2000, STAR, EARTH, SITEV)
subroutine bkplh (XYZ, PLH, PI, A, FL)
subroutine sitblk (Kerr)
subroutine ocnin (Kerr)
Function/Subroutine Documentation
bkplh()
subroutine bkplh (real*8, dimension(3) XYZ, real*8, dimension(3) PLH, real*8 PI, real*8 A, real*8 FL)
Definition at line 1226 of file csitm.f.
Referenced by siti().
ocnin()
subroutine ocnin (integer*2, dimension(10) Kerr)
Definition at line 1461 of file csitm.f.
References ckill(), and putr().
Referenced by siti().
sita()
subroutine sita ()
Definition at line 2 of file csitm.f.
References adda(), addi(), and addr().
sitblk()
subroutine sitblk (integer*2, dimension(10) Kerr)
Definition at line 1347 of file csitm.f.
References ckill(), puti(), and putr().
Referenced by siti().
sitg()
subroutine sitg (real*8, dimension(2) AXOFF, real*8, dimension(3) CFBASE, real*8, dimension(3,2) CFLAT, real*8, dimension(3,2) CFLON, real*8, dimension(3,2) CFSITE, real*8, dimension(3,2) CFSITN, integer*2, dimension(2) KAXIS, real*8, dimension(11,3,2) OCEAMP, real*8, dimension(11,3,2) OCEPHS, real*8, dimension(2) SITLAT, real*8, dimension(2) SITLON, real*8, dimension(2) SITRAD, real*8, dimension(3,3,2) TCTOCF, real*8, dimension(3,3,2) RTTOCF, real*8, dimension(2) ZPATH, real*8, dimension(2) SITHEIGHT, real*8, dimension(2) GEOLAT)
Definition at line 714 of file csitm.f.
References ckill(), geti(), and vecsb().
Referenced by drivr().
siti()
subroutine siti ()
Definition at line 118 of file csitm.f.
References bkplh(), ckill(), get4(), geti(), mmul2(), ocnin(), puta(), putr(), rotat(), and sitblk().
Referenced by initl().
sitp()
subroutine sitp (real*8, dimension(3,3,3) R2000, real*8, dimension(3) STAR, real*8, dimension(3,3) EARTH, real*8, dimension(3,2) SITEV)
Definition at line 1014 of file csitm.f.
References dotp(), and put4().
Referenced by drivr().