cstrm.f File Reference
Functions/Subroutines
subroutine stra
subroutine stri
subroutine strg (XJD, UTC, STAR)
subroutine strp (EPBASE, STAR, EARTH, SITEV, DSTRP, CDX, CRAX, SDX, SRAX)
subroutine strc (DSTRP)
subroutine strin (Kerr)
Function/Subroutine Documentation
stra()
subroutine stra ()
Definition at line 2 of file cstrm.f.
References adda(), addr(), and delr().
strc()
subroutine strc (real*8, dimension(2,2) DSTRP)
Definition at line 945 of file cstrm.f.
References put4().
Referenced by drivr().
strg()
subroutine strg (real*8 XJD, real*8 UTC, real*8, dimension(3) STAR)
Definition at line 510 of file cstrm.f.
References ckill(), geti(), and jdy2k().
Referenced by drivr().
stri()
subroutine stri ()
Definition at line 183 of file cstrm.f.
References ckill(), get4(), geta(), geti(), put4(), puta(), and strin().
Referenced by initl().
strin()
subroutine strin (integer*2, dimension(3) Kerr)
Definition at line 1030 of file cstrm.f.
References ckill(), puta(), and putr().
Referenced by stri().
strp()
subroutine strp (real*8, dimension(3,2) EPBASE, real*8, dimension(3) STAR, real*8, dimension(3,3) EARTH, real*8, dimension(3,2) SITEV, real*8, dimension(2,2) DSTRP, real*8 CDX, real*8 CRAX, real*8 SDX, real*8 SRAX)
Definition at line 746 of file cstrm.f.
References dotp(), and put4().
Referenced by drivr().