cstrt.f File Reference
Functions/Subroutines
subroutine start (ILU, CALCON_NAME, Iout)
subroutine staa
subroutine stai
subroutine upper (Isize, Iup, String)
real *8 function jdy2k (IYEAR, IMONTH, IDAY)
Function/Subroutine Documentation
jdy2k()
real*8 function jdy2k (integer*4 IYEAR, integer*4 IMONTH, integer*4 IDAY)
Definition at line 536 of file cstrt.f.
Referenced by strg().
staa()
subroutine staa ()
Definition at line 297 of file cstrt.f.
References adda(), addi(), and addr().
stai()
subroutine stai ()
Definition at line 371 of file cstrt.f.
References put4(), puta(), and puti().
Referenced by initl().
start()
subroutine start (integer*2 ILU, character*128 CALCON_NAME, integer*2 Iout)
Definition at line 2 of file cstrt.f.
upper()
subroutine upper (integer*4 Isize, integer*4 Iup, character*(*) String)
Definition at line 478 of file cstrt.f.