ctheu.f File Reference
Functions/Subroutines
subroutine thera
subroutine theri
subroutine thery (DATMC, DAXOC, DIONC, DLPGR, EARTH, EPBASE, SITEP, SITEV, SITEA, SUN, STAR, XMOON, AT)
subroutine consen (DATMC, EARTH, EPBASE, SITEP, SITEV, SITEA, SUN, XMOON, STAR, tg2_tg1, dtg2_tg1, delta_t_grav, d_delta_t_grav, delta_t_grav_Sun, d_delta_t_grav_Sun, Con_part, Bend_par, Sunplus)
Function/Subroutine Documentation
consen()
subroutine consen (real*8, dimension(2,2) DATMC, real*8, dimension(3,3) EARTH, real*8, dimension(3,2) EPBASE, real*8, dimension(3,2) SITEP, real*8, dimension(3,2) SITEV, real*8, dimension(3,2) SITEA, real*8, dimension(3,2) SUN, real*8, dimension(3,2) XMOON, real*8, dimension(3) STAR, real*8 tg2_tg1, real*8 dtg2_tg1, real*8 delta_t_grav, real*8 d_delta_t_grav, real*8 delta_t_grav_Sun, real*8 d_delta_t_grav_Sun, real*8, dimension(2) Con_part, real*8, dimension(2) Bend_par, real*8, dimension(2) Sunplus)
Definition at line 493 of file ctheu.f.
References dotp(), put4(), vecad(), vecmg(), vecsb(), and vunit().
Referenced by thery().
thera()
subroutine thera ()
Definition at line 2 of file ctheu.f.
References adda(), addr(), dela(), and delr().
theri()
subroutine theri ()
Definition at line 135 of file ctheu.f.
References puta().
Referenced by initl().
thery()
subroutine thery (real*8, dimension(2,2) DATMC, real*8, dimension(2,2) DAXOC, real*8, dimension(2) DIONC, real*8 DLPGR, real*8, dimension(3,3) EARTH, real*8, dimension(3,2) EPBASE, real*8, dimension(3,2) SITEP, real*8, dimension(3,2) SITEV, real*8, dimension(3,2) SITEA, real*8, dimension(3,2) SUN, real*8, dimension(3) STAR, real*8, dimension(3,2) XMOON, real*8 AT)
Definition at line 216 of file ctheu.f.
References consen(), and put4().
Referenced by drivr().