cut1m.f File Reference
Functions/Subroutines
subroutine ut1a
subroutine ut1i
subroutine ut1g (AT, DUTCAT, UTC, XJD, CT, fa, fad, tc2000, TSKIP, DUT1AT, UT1)
subroutine ut1p (CFBASE, DIURNV, GAST, RDNP, RN, RP, RW, STAR, EARTH, DUT1P)
subroutine ut1mu (XJD, CT, fa, fad, tc2000, ATMUT1, SHORTP, DIVUTC)
subroutine ut1szt (fa, fad, DUT, DLOD, DOMEGA)
integer *4 function get_leapsec (xjd, xleap)
subroutine spline (xa, ya, n, yp1, ypn, y2, ierr4)
subroutine splint4 (xa, ya, y2, n, x, y, ydot, ydot2, ydot3, ierr4)
Function/Subroutine Documentation
get_leapsec()
integer*4 function get_leapsec (real*8 xjd, real*8, dimension(5) xleap)
Definition at line 1594 of file cut1m.f.
spline()
subroutine spline (real*8, dimension(20) xa, real*8, dimension(20) ya, integer*4 n, real*8 yp1, real*8 ypn, real*8, dimension(20) y2, integer*4 ierr4)
Definition at line 1693 of file cut1m.f.
Referenced by ut1i(), and wobi().
splint4()
subroutine splint4 (real*8, dimension(20) xa, real*8, dimension(20) ya, real*8, dimension(20) y2, integer*4 n, real*8 x, real*8 y, real*8 ydot, real*8 ydot2, real*8 ydot3, integer*4 ierr4)
Definition at line 1821 of file cut1m.f.
Referenced by ut1mu(), and wobmu().
ut1a()
subroutine ut1a ()
Definition at line 2 of file cut1m.f.
References adda(), addi(), addr(), ask(), dela(), and delr().
Referenced by calcinit().
ut1g()
subroutine ut1g (real*8 AT, real*8 DUTCAT, real*8 UTC, real*8 XJD, real*8 CT, real*8, dimension(5) fa, real*8, dimension(5) fad, real*8 tc2000, integer*4 TSKIP, real*8 DUT1AT, real*8 UT1)
Definition at line 724 of file cut1m.f.
References put4(), and ut1mu().
Referenced by drivr().
ut1i()
subroutine ut1i ()
Definition at line 142 of file cut1m.f.
References ckill(), get4(), geti(), nutfa(), put4(), puta(), puti(), spline(), ut1mu(), and ut1szt().
Referenced by initl().
ut1mu()
subroutine ut1mu (real*8 XJD, real*8 CT, real*8, dimension(5) fa, real*8, dimension(5) fad, real*8 tc2000, real*8 ATMUT1, real*8 SHORTP, real*8 DIVUTC)
Definition at line 1093 of file cut1m.f.
References ckill(), splint4(), and ut1szt().
Referenced by ut1g(), and ut1i().
ut1p()
subroutine ut1p (real*8, dimension(3) CFBASE, real*8 DIURNV, real*8, dimension(2) GAST, real*8, dimension(3,3) RDNP, real*8, dimension(3,3,2) RN, real*8, dimension(3,3,2) RP, real*8, dimension(3,3,2) RW, real*8, dimension(3) STAR, real*8, dimension(3,3) EARTH, real*8, dimension(2,2) DUT1P)
Definition at line 886 of file cut1m.f.
References d3rot(), ddrot(), dotp(), drott(), mmul5(), put4(), and vecrt().
Referenced by drivr().
ut1szt()
subroutine ut1szt (real*8, dimension(5) fa, real*8, dimension(5) fad, real*8 DUT, real*8 DLOD, real*8 DOMEGA)
Definition at line 1402 of file cut1m.f.
Referenced by ut1i(), and ut1mu().