cutcu.f File Reference
Functions/Subroutines
subroutine utctm (UTC, XJD)
Function/Subroutine Documentation
utctm()
subroutine utctm (real*8 UTC, real*8 XJD)
Definition at line 2 of file cutcu.f.
References ckill(), get4(), and geti().
Referenced by drivr().