cuvm.f File Reference
Functions/Subroutines
subroutine uva
subroutine uvg (STAR, EPBASE)
Function/Subroutine Documentation
uva()
subroutine uva ()
Definition at line 2 of file cuvm.f.
References addr().
uvg()
subroutine uvg (real*8, dimension(3) STAR, real*8, dimension(3,2) EPBASE)
Definition at line 38 of file cuvm.f.
References ckill(), crosp(), get4(), put4(), vecmg(), and vunit().
Referenced by drivr().