cvecu.f File Reference
Functions/Subroutines
subroutine vecad (A, B, C)
subroutine vecsb (A, B, C)
real *8 function dotp (A, B)
real *8 function vecmg (A)
subroutine vunit (A, B)
subroutine crosp (A, B, C)
Function/Subroutine Documentation
crosp()
subroutine crosp (real*8, dimension(3) A, real*8, dimension(3) B, real*8, dimension(3) C)
Definition at line 404 of file cvecu.f.
Referenced by axog(), plxp(), and uvg().
dotp()
real*8 function dotp (real*8, dimension(3) A, real*8, dimension(3) B)
Definition at line 165 of file cvecu.f.
Referenced by consen(), ocec(), sitp(), strp(), ut1p(), and wobp().
vecad()
subroutine vecad (real*8, dimension(3) A, real*8, dimension(3) B, real*8, dimension(3) C)
Definition at line 2 of file cvecu.f.
Referenced by atmg(), axog(), consen(), etdc8(), etdg(), oceg(), and sitcr().
vecmg()
real*8 function vecmg (real*8, dimension(3) A)
Definition at line 246 of file cvecu.f.
Referenced by consen(), and uvg().
vecsb()
subroutine vecsb (real*8, dimension(3) A, real*8, dimension(3) B, real*8, dimension(3) C)
Definition at line 84 of file cvecu.f.
Referenced by consen(), etdc(), ocec(), ptdc(), ptdp(), sitcr(), and sitg().
vunit()
subroutine vunit (real*8, dimension(3) A, real*8, dimension(3) B)
Definition at line 322 of file cvecu.f.
Referenced by atmg(), consen(), etdc8(), etdg(), and uvg().