cvrtuc.c File Reference
Functions
char * cvrtuc (char *s)
char * cvrtlc (char *s)
Function Documentation
cvrtlc()
char* cvrtlc (char * s)
Definition at line 37 of file cvrtuc.c.
Referenced by cvrtuc().
cvrtuc()
char* cvrtuc (char * s)
Definition at line 12 of file cvrtuc.c.
References cvrtlc().
Referenced by c_fetch(), d_fetch(), f_fetch(), i_fetch(), mjd_fetch(), and n_rows_().