cwobm.f File Reference
Functions/Subroutines
subroutine woba
subroutine wobi
subroutine wobg (CT, UTC, XJD, TSKIP, RW, WOBXR, WOBYR)
subroutine wobp (CFBASE, RDNP, RN, RP, RS, STAR, EARTH)
subroutine wobc
subroutine wobmu (XJD, tab_time, WOBXL, WOBYL, DWOBXL, DWOBYL)
Function/Subroutine Documentation
woba()
subroutine woba ()
Definition at line 2 of file cwobm.f.
References adda(), addr(), ask(), dela(), and delr().
Referenced by calcinit().
wobc()
subroutine wobc ()
Definition at line 1089 of file cwobm.f.
References put4().
Referenced by drivr().
wobg()
subroutine wobg (real*8 CT, real*8 UTC, real*8 XJD, integer*4 TSKIP, real*8, dimension(3,3,2) RW, real*8 WOBXR, real*8 WOBYR)
Definition at line 601 of file cwobm.f.
References drott(), madd2(), mmul2(), put4(), rotat(), and wobmu().
Referenced by drivr().
wobi()
subroutine wobi ()
Definition at line 148 of file cwobm.f.
References ckill(), get4(), put4(), puta(), spline(), and wobmu().
Referenced by initl().
wobmu()
subroutine wobmu (real*8 XJD, real*8 tab_time, real*8 WOBXL, real*8 WOBYL, real*8 DWOBXL, real*8 DWOBYL)
Definition at line 1183 of file cwobm.f.
References ckill(), and splint4().
Referenced by wobg(), and wobi().
wobp()
subroutine wobp (real*8, dimension(3) CFBASE, real*8, dimension(3,3) RDNP, real*8, dimension(3,3,2) RN, real*8, dimension(3,3,2) RP, real*8, dimension(3,3,3) RS, real*8, dimension(3) STAR, real*8, dimension(3,3) EARTH)
Definition at line 820 of file cwobm.f.
References ddrot(), dotp(), drott(), madd2(), madd4(), mmul2(), mmul5(), put4(), and vecrt().
Referenced by drivr().