interface.f File Reference
Functions/Subroutines
subroutine get4 (VARNAM, RVARB, NDIM1, NDIM2, NDIM3, NDO, IERR)
subroutine geti (VARNAM, IVARB, NDIM1, NDIM2, NDIM3, NDO, IERR)
subroutine geta (VARNAM, LVARB, NDIM1, NDIM2, NDIM3, NDO, IERR)
subroutine put4 (STR1, STR2, NCHR2, N1, N2)
subroutine delr (N1, STR1)
subroutine dela (N1, STR1)
subroutine putr (STR1, STR2, NCHR2, N1, N2)
subroutine puta (STR1, STR2, NCHR2, N1, N2)
subroutine puti (STR1, STR2, NCHR2, N1, N2)
subroutine adda (N1, STR1, STR2, NSTR2, N2, N3)
subroutine addr (N1, STR1, STR2, NSTR2, N2, N3)
subroutine addi (N1, STR1, STR2, NSTR2, N2, N3)
Function/Subroutine Documentation
adda()
subroutine adda (integer*2 N1, character*8 STR1, character*32 STR2, integer*2 NSTR2, integer*2 N2, integer*2 N3)
Definition at line 1149 of file interface.f.
Referenced by atima(), atma(), axoa(), ctima(), etda(), nuta(), ocea(), pepa(), plxa(), prea(), ptda(), sita(), staa(), stra(), thera(), ut1a(), and woba().
addi()
subroutine addi (integer N1, character*8 STR1, character*32 STR2, integer NSTR2, integer N2, integer N3)
Definition at line 1170 of file interface.f.
Referenced by sita(), staa(), and ut1a().
addr()
subroutine addr (integer N1, character*8 STR1, character*32 STR2, integer NSTR2, integer N2, integer N3)
Definition at line 1157 of file interface.f.
Referenced by atma(), axoa(), ctima(), dirna(), etda(), m2000a(), nuta(), ocea(), pepa(), plxa(), prea(), ptda(), sita(), staa(), stra(), thera(), ut1a(), uva(), and woba().
dela()
subroutine dela (integer*2 N1, character*14 STR1)
Definition at line 1091 of file interface.f.
Referenced by pepa(), thera(), ut1a(), and woba().
delr()
subroutine delr (integer*2 N1, character*14 STR1)
Definition at line 1081 of file interface.f.
Referenced by atma(), axoa(), dirna(), etda(), nuta(), stra(), thera(), ut1a(), and woba().
get4()
subroutine get4 (character*14 VARNAM, real*8, dimension(ndim1,ndim2,ndim3) RVARB, integer*2 NDIM1, integer*2 NDIM2, integer*2 NDIM3, integer*2 NDO, integer*2 IERR)
Definition at line 2 of file interface.f.
Referenced by atimi(), atmp(), axog(), ctimi(), geta(), geti(), initl(), obsnt(), prei(), siti(), stri(), ut1i(), utctm(), uvg(), and wobi().
geta()
subroutine geta (character*14 VARNAM, integer*2, dimension(4,20) LVARB, integer*2 NDIM1, integer*2 NDIM2, integer*2 NDIM3, integer*2 NDO, integer*2 IERR)
Definition at line 750 of file interface.f.
References get4().
Referenced by obsnt(), and stri().
geti()
subroutine geti (character*14 VARNAM, integer*2, dimension(ndim1,ndim2,ndim3) IVARB, integer*2 NDIM1, integer*2 NDIM2, integer*2 NDIM3, integer*2 NDO, integer*2 IERR)
Definition at line 635 of file interface.f.
References get4().
Referenced by obsnt(), sitg(), siti(), strg(), stri(), ut1i(), and utctm().
put4()
subroutine put4 (character*14 STR1, real*8, dimension(nchr2,n1) STR2, integer*2 NCHR2, integer*2 N1, integer*2 N2)
Definition at line 839 of file interface.f.
Referenced by atmc(), atmg(), atmp(), axoc(), axog(), axop(), consen(), ctimg(), dirnc(), etdc(), etdp(), m2000(), nutc(), nutg(), nutp(), ocec(), oceg(), pep(), plxc(), plxp(), prep(), ptdc(), ptdp(), sitp(), stai(), strc(), stri(), strp(), thery(), ut1g(), ut1i(), ut1p(), uvg(), wobc(), wobg(), wobi(), and wobp().
puta()
subroutine puta (character*14 STR1, character*1, dimension(2*nchr2) STR2, integer*2 NCHR2, integer*2 N1, integer*2 N2)
Definition at line 1120 of file interface.f.
Referenced by atimi(), atmi(), axoi(), calcinit(), ctimi(), etdi(), nuti(), ocei(), pepi(), plxi(), prei(), ptdi(), siti(), stai(), stri(), strin(), theri(), ut1i(), and wobi().
puti()
subroutine puti (character*14 STR1, integer*2, dimension(nchr2) STR2, integer*2 NCHR2, integer*2 N1, integer*2 N2)
Definition at line 1135 of file interface.f.
Referenced by sitblk(), stai(), and ut1i().
putr()
subroutine putr (character*14 STR1, real*8, dimension(nchr2,n1) STR2, integer*2 NCHR2, integer*2 N1, integer*2 N2)
Definition at line 1101 of file interface.f.
Referenced by ocnin(), sitblk(), siti(), and strin().