iword.c File Reference
#include <string.h>
Functions
int sindex (char *s, char *t)
int iword (char *instr, char *delim, int nword, char *outstr)
Function Documentation
iword()
int iword (char * instr, char * delim, int nword, char * outstr)
Definition at line 7 of file iword.c.
References sindex().
Referenced by init_ast_dopplr().
sindex()
int sindex (char * s, char * t)
Referenced by iword().