mjd2str.c File Reference
#include <stdio.h>
#include <string.h>
#include `vlb.h`
Macros
#define AD 678576
Functions
STATUS mjd2date (long mjd, int *pYear, int *pMonth, int *pDay)
char * mjd2str (long mjd, char *pstring)
STATUS mjd2dayno (long mjd, int *pDayNo)
Macro Definition Documentation
AD
#define AD 678576
Referenced by mjd2date().
Function Documentation
mjd2date()
STATUS mjd2date (long mjd, int * pYear, int * pMonth, int * pDay)
Definition at line 18 of file mjd2str.c.
References AD, and ERROR.
Referenced by mjd2dayno(), and mjd2str().
mjd2dayno()
STATUS mjd2dayno (long mjd, int * pDayNo)
Definition at line 119 of file mjd2str.c.
References mjd2date(), and OK.
Referenced by mjd2str().
mjd2str()
char* mjd2str (long mjd, char * pstring)
Definition at line 85 of file mjd2str.c.
References ERROR, mjd2date(), and mjd2dayno().
Referenced by date2str(), and time2str().