mvrec.f File Reference
Functions/Subroutines
subroutine mvrec (N1, N2, N3, KERR)
integer *2 function getunit (I1)
subroutine finis (IERR)
subroutine ask (CHR8, I1, I2, I3, I4, I5, I6, I7, I8)
subroutine wridr
Function/Subroutine Documentation
ask()
subroutine ask (character*8 CHR8, integer I1, integer I2, integer I3, integer I4, integer I5, integer I6, integer I7, integer I8)
Definition at line 30 of file mvrec.f.
Referenced by ut1a(), and woba().
finis()
subroutine finis (IERR)
Definition at line 25 of file mvrec.f.
Referenced by ckill(), and obsnt().
getunit()
integer*2 function getunit (integer*2 I1)
Definition at line 19 of file mvrec.f.
mvrec()
subroutine mvrec (integer N1, integer N2, integer N3, integer KERR)
Definition at line 8 of file mvrec.f.
Referenced by initl(), and obsnt().
wridr()
subroutine wridr ()
Definition at line 40 of file mvrec.f.
Referenced by initl().