time2str.c File Reference
#include <ctype.h>
#include <string.h>
#include <stdio.h>
#include `MATHCNST.H`
#include `vlb.h`
Functions
char * mjd2str (long mjd, char *pstring)
char * rad2strg (double angle, char *pFormat, char *pOutStr, BOOL roundFlag)
char * rad2str (double angle, char *pFormat, char *pOutStr)
char * time2str (double inTime, char *pFormat, char *pOutStr)
char * timeMjd2str (double inTime, char *pOutStr)
Function Documentation
mjd2str()
char* mjd2str (long mjd, char * pstring)
Definition at line 85 of file mjd2str.c.
References ERROR, mjd2date(), and mjd2dayno().
Referenced by time2str().
rad2str()
char* rad2str (double angle, char * pFormat, char * pOutStr)
Definition at line 279 of file time2str.c.
References rad2strg(), and time2str().
Referenced by date2str(), and time2str().
rad2strg()
char* rad2strg (double angle, char * pFormat, char * pOutStr, BOOL roundFlag)
Definition at line 116 of file time2str.c.
References FALSE, and isdigit.
Referenced by rad2str().
time2str()
char* time2str (double inTime, char * pFormat, char * pOutStr)
Definition at line 297 of file time2str.c.
References mjd2str(), NULL, rad2str(), and timeMjd2str().
Referenced by rad2str(), and timeMjd2str().
timeMjd2str()
char* timeMjd2str (double inTime, char * pOutStr)
Definition at line 342 of file time2str.c.
References time2str().
Referenced by time2str().